name: Veracode IaC/Secrets Scanning

run-name: Veracode IaC/Secrets Scanning - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-iac-secrets-scan]
    
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: GitHubVeracode/veracode-github-app@main
      id: 'create_check_run'
      with:
        name: 'Register workflow'
        head_sha: ${{ github.event.client_payload.sha }}
        owner: ${{ github.event.client_payload.repository.owner }}
        repo: ${{ github.event.client_payload.repository.name }}
        status: 'in_progress'
        event_type: ${{ github.event.client_payload.event_type }}
        github_token: ${{ github.event.client_payload.token }}
       
  veracode-iac-secrets-scan:
    needs: [register]
    runs-on: ubuntu-latest
    name: Veracode IaC/Secrets Scanning

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
      - name: Run Veracode IaC/Secrets Scanning
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
            vid: ${{ secrets.API_ID }}
            vkey: ${{ secrets.API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: false
            fail_build: true
